AWSTemplateFormatVersion: 2010-09-09
Description: >-
  goshenkata-backend

Transform:
- AWS::Serverless-2016-10-31

Globals:
  Api:
    Auth:
      DefaultAuthorizer: CognitoAuthorizer
      Authorizers:
        CognitoAuthorizer:
          UserPoolArn: arn:aws:cognito-idp:eu-central-1:207567768006:userpool/eu-central-1_VG1OzzrL0
Resources:
  createEntryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/create-entry.createEntryHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref DiaryTable
      Environment:
        Variables:
          DIARY_TABLE: !Ref DiaryTable
          ALLOWED_USER_EMAIL: goshenkataklev@gmail.com
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST
            Auth:
              ApiKeyRequired: true
  GoshenkataApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: goshenkata-api-key
      Enabled: true
      StageKeys:
        - RestApiId: !Ref ServerlessRestApi
          StageName: Prod
  DiaryTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: userId
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 4
        WriteCapacityUnits: 4
  GoshenkataUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: goshenkata-usage-plan
      ApiStages:
        - ApiId: !Ref ServerlessRestApi
          Stage: Prod
      Description: Usage plan for goshenkata API
      UsagePlanThrottle:
        BurstLimit: 100
        RateLimit: 50

  GoshenkataUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref GoshenkataApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref GoshenkataUsagePlan

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
