name: Deploy frontend + terraform

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-central-1

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - name: Get Git Commit Hash
      id: git-hash
      run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Terraform Apply
      working-directory: terraform
      run: terraform apply -auto-approve -var="deployment_id=${{ steps.git-hash.outputs.hash }}"

    - name: Deploy backend using SAM
      uses: aws-actions/setup-sam@v2
      with:
        use-installer: true
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: SAM Build
      working-directory: backend
      run: sam build --use-container
    
    - name: SAM Deploy
      working-directory: backend
      run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
